include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_const_constructors: true
    prefer_const_declarations: true
    avoids_empty_else: true
    empty_statements: true
    avoid_print: true
